### ISSUE TITLE
El proyecto no abre! es la intención ?

### ISSUE THREAD

**Issue by DanielThompkins** [Skeiceee/Genericlothing#8]
Hola! Por más que seguí las instrucciones nunca logre que pasara del 404, me imagino que  es la intención! Saludos!

**Comment by Skeiceee** [comment]
Para nada debería ser funcional, quizás falta correr el siguiente comando:
`php artisan key:generate`

El sistema esta hecho con el Framework Laravel (https://laravel.com/) si quiere ver todo lo que ofrece el Framework y como se despliega una aplicación echa en Laravel.

El problema es que se tiene que crear los siguientes módulos:
1. Módulos para poder controlar los proveedores.
2. Modulo para generar el pago de la compra (Sistema de pago).

**Comment by DanielThompkins** [comment]
Voy manejando....estacionó y te respondo.... Muchas gracias!

**Comment by DanielThompkins** [comment]
Hola Víctor Buenas Noches...pues estuve hasta hace 10 minutos tratando de
correrlo... Estoy trabajando en pasarelas de pago Paypal y Mercado Pago...
Voy a intentar como me dices en el correo.. en realidad también le coloque
algunas llaves más en el .env .. estoy admirado por el código... Muchas
gracias. En realidad pienso subir mi código apenas esté listo en su primera
versión pero nada que ver con este repositorio. Reviso y no mando más
issue.

**Comment by DanielThompkins** [comment]
Ok, aun sigue sin abrir , coloque aún más datos en el .env que sé que se necesitan para correr , también aplique el comando de artisan , y aun sigue dando el error 404! Muchas Gracias!

**Comment by Skeiceee** [comment]
Yo monte el sistema nuevamente para probar y todo esta funcionando.
